version: '3'
services:
  Drupal:
    image: drupal
    deploy:
      replicas: 3
    networks:
    - mydrupal
    ports:
    - "8080:8081"
  postgres:
    image: postgres
    networks:
    - mydrupal
    environment:
    - POSTGRES_PASSWORD=123456
networks:
  mydrupal: